### ISSUE TITLE
App crash case in AudioRecord

### ISSUE THREAD

**Issue by nageshnayak** [SomnathS09/SAS-Example-App#7]
Reproducible steps:
Press Initialize
Press Set Path
Press Play Recording
App crashes

Need to check if same steps cause crash in media recorder

**Comment by SomnathS09** [comment]
Yes, because that file is not created yet, so FileNotFound exception, i.e. Media player can't find the file to play.

**Comment by SomnathS09** [comment]
setOutputFile() method creates a blank "FileName.wav" (without headers), but MediaPlayer cannot play blank files and returns IOException.

**Comment by nageshnayak** [comment]
Can't we handle the exception rather than crashing?

**Comment by SomnathS09** [comment]
Yes, we can.
I'll add a toast message saying "Can't play this file"

**Comment by nageshnayak** [comment]
Check needed in MediaRecorder build as well

**Comment by nageshnayak** [comment]
Reproducible steps:
Press Initialize
Press Set Path
Press Prepare
Press Play Recording
App crashes

**Comment by nageshnayak** [comment]
Same sequence works fine for AudioRecord build
